### ISSUE TITLE
Why the AddEncrypt is not supported in the SDK

### ISSUE THREAD

**Issue by winterpi** [lucasmenendez/gopaillier#1]
Thank you for your good work for go paillier.
It's very useful for make float number operation with the SDK.
But I'm curious why the AddEncrypt is not supported?

**Comment by lucasmenendez** [comment]
Thanks for the feedback! 

The aim of the SDK is allow to perform operations using raw numbers over an encrypted one, supporting hypothetical uses cases such as Privacy Preserving Data Sharing, where A wants to share an encrypted data with a third party to perform some operations (in that example is not necessary that the third party encrypts its data).

If you want to perform addition between encrypted numbers, you can use the [gopaillier/pkg/paillier](https://github.com/lucasmenendez/gopaillier/blob/main/pkg/paillier/paillier.go) package, that implements the `PublicKey. AddEncrypted(a, b *big.Int)` function. It is perfectly compatible with the [gopaillier/pkg/number](https://github.com/lucasmenendez/gopaillier/tree/main/pkg/number/number.go) package, using the same logic that is already implemented in the SDK `Add(key *paillier.PublicKey, encrypted, input *number.Number)` operation.

**Comment by winterpi** [comment]
Thank you for your suggestion.
I already implemented it with the same logic of SDK Add(key *paillier.PublicKey, encrypted, input *number.Number)
